FROM node:14.16.0-alpine3.13 As build-stage
WORKDIR /app
COPY package.json .
RUN npm install
COPY . . 
ENV REACT_APP_API_URL=http://165.227.81.34:4000

RUN npm run build; 

# step 2 form production
FROM nginx:1.12-alpine 
# RUN addgroup app && adduser -S -G app app
# USER app
# COPY --from=build-stage /app/build /usr/share/nginx/html/

COPY --from=build-stage /app/build /var/www
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80 
ENTRYPOINT [ "nginx","-g", "daemon off;" ]%  